### ISSUE TITLE
Google Analytics?

### ISSUE THREAD

**Issue by mnot** [OpenSprinkler/Weather-Adjustment#1]
Hi!

What are the requests to google analytics in the code for?

If you're using them to gather data about usage to improve the app, it'd be good to disclose that in README...

**Comment by salbahra** [comment]
Hi Mark,

I think putting a disclosure is a good idea and will add that soon.

Right now we are collecting whether the Zimmerman method is being used or just timezone info is being requested which tells us how many users are using weather adjustments.

We also save the firmware version in order to trend how often people are upgrading to assess if an easier upgrade method is necessary (which I think it is).

Lastly, we are saving the location which we hoped to use to troubleshoot location look up problems however this seems not to be necessary as Weather Underground does a great job and will likely not be tracked in the future.

Thank you

**Comment by salbahra** [comment]
I added some description and disclosures to the readme. Going to mark this ticket as closed now.

**Comment by mnot** [comment]
Thanks!
